CREATE TABLE weather (
    station text,
    station_name text,
    elevation text,
    latitude text,
    longitude text,
    date_time text,
    HPCP text,
    measurement_flag text,
    quality_flag text
);

status,
duration,
start_date,
strt_statn,
end_date,
end_statn,
bike_nr,
subsc_type,
zip_code,
birth_date,
gender,
start_municipal,
start_lat,
start_lng,
end_municipal,
end_lat,
end_lng,
start_hpcp,
end_hpcp,driver_age,travel_distance,
average_speed,
start_year,
start_month,
start_weekday,s
tart_hour,
end_year,
end_month,
end_weekday,
end_hour,
is_start_holiday,
is_start_working_day,
is_start_weekend,
start_year_part,
is_start_Boston,
is_start_Brookline,
is_start_Cambridge,
is_start_Somerville,
is_end_Boston,
is_end_Brookline,
is_end_Cambridge,
is_end_Somerville,
is_end_Female,
is_end_Male,
is_start_0,
is_start_1,
is_start_2,
is_start_3,
is_start_4,
is_start_5,is_start_6,is_start_7,is_start_8,is_start_9,is_start_10,is_start_11,is_start_12,is_start_13,is_start_14,is_start_15,is_start_16,is_start_17,is_start_18,is_start_19,is_start_20,is_start_21,is_start_22,is_start_23,is_end_0,is_end_1,is_end_2,is_end_3,is_end_4,is_end_5,is_end_6,is_end_7,is_end_8,is_end_9,is_end_10,is_end_11,is_end_12,is_end_13,is_end_14,is_end_15,is_end_16,is_end_17,is_end_18,is_end_19,is_end_20,is_end_21,is_end_22,is_end_23,is_start_11Q3,is_start_11Q4,is_start_12Q1,is_start_12Q2,is_start_12Q3,
is_station_diff,
daily_in_flow_count,
daily_out_flow_count